version: "3.8"

services:
  database:
    build: .
    container_name: cryptic_creatures_db
    ports:
      - "5432:5432"
    volumes:
      - CrypticCreaturesDB-data:/var/lib/postgresql/data/

    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password123
      - POSTGRES_DB=CrypticCreaturesDB
  
  adminer:
    image: adminer
    restart: always
    depends_on:
      - database
    ports:
      - "9090:8080"

    # usage of adminer:
    # http://localhost:9090
    # for server fill in 'database'


volumes:
  CrypticCreaturesDB-data: # named volumes can be managed easier using docker-compose